package com.capgemini.librarymanagementsystem;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class LibraryManagementSystemSecurityApplicationInitializer extends AbstractSecurityWebApplicationInitializer{

}
